config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root              'static_pages#home'
  resource :peers
  get '/users', to: "controllers#index"

  get 'planos'   =>  'static_pages#planos'
  get 'home'     =>  'static_pages#home'
  get 'about'    =>  'static_pages#about'

  resource :aulas
  get '/aulas', to: "aulas#index"
  get '/aulas/new', to: "aulas#new"
  #post '/aulas/create', to "aulas#create"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/aula.rb
class Aula < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  attr_accessor :idade

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:idade])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:idade])
    devise_parameter_sanitizer.permit(:account_update, keys: [:idade])
  end
end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
	def show
		@aulas = Aula.page params[:page]
	end

	def create
		puts "chamou aqui"
		@aula = Aula.new(aula_params)
		respond_to do |format|
			if @aula.save
				format.html { redirect_to aulas_path, notice: "Aula adicionada com sucesso !"}
			end
		end
	end

	def new
		@aula = Aula.new
	end

	private
	def aula_params
      params.require(:aula).permit(:nome, :description, :image_url)
    end
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
  
  private

    def cliente_params
      params.require(:cliente).permit(:nome, :idade, :planos, :cpf)
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]



  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

   #If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
  devise_parameter_sanitizer.permit(:sign_up, keys: [:idade])
    end

  #If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:idade])
   end

   def configure_sign_in_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :idade])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aulas/index.html.erb
<%provide(:title, 'Testando') %>

<div>
	<p><%= flash[:notice] %></p>
	
	<%= @aulas.each do |aula| %>
		<div>
			<%= image_tag aula.image_Url %>
			<h3> <%= aula.nome %> </h3>
			<p>	<%= aula.description %> </p>

		</div>
	<% end %>
</div>

app/views/aulas/new.html.erb
<%= form_with(model: @aula) do |f| %>
	<div>
		<%= f.label :nome, "Nome" %>
		<%= f.text_field :nome, class:"" %> 
	</div>

	<div>
		<%= f.label :image_url, "Imagem url" %>
		<%= f.text_field :image_url, class:"",placeholder:"http://" %> 
	</div>

	<div>
		<%= f.label :description, "Descrição" %>
		<%= f.text_area :description, class:"" %> 
	</div>

	<%= f.submit "Salvar" %>


<% end %>

app/views/aulas/show.html.erb
<% provide(:title, 'Aulas') %>

<div>
  <h1>CONHEÇA NOSSAS AULAS!</h1>
</div>
<hr>

<div class="btns">
  <%= image_tag("aulas/musculacao", class: "photo", width: "250", height: "300") %>

  <%= image_tag("aulas/body_combat", class: "photo", width: "250", height: "300") %>

  <%= image_tag("aulas/fit", class: "photo", width: "250", height: "300") %>

  <%= link_to "#", id: "prev-link" do %>Previous Page<% end %>
  <%= link_to "#", id: "next-link" do %>Next Page<% end %>
</div>

<div id="photo-container"></div>

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>" class="client-card">
  <h2 class="client-card__name">
    <strong>Nome:</strong>
    <%= cliente.nome %>
  </h2>

  <h2 class="client-card__age">
    <strong>Idade:</strong>
    <%= cliente.idade %>
  </h2>

  <h2 class="client-card__cpf">
    <strong>Cpf:</strong>
    <%= cliente.cpf %>
  </h2>

  <h2 class="client-card__plan">
    <strong>Plano:</strong>
    <%= cliente.planos %>
  </h2>

</div>

app/views/clientes/_form.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <title>Bootstrap Example</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="p-3 m-0 border-0 bd-example">


    <%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  </div>

  <div class="main-content">

    <%= image_tag("logo/logotipo_", class: "photo", width: "250", height: "250") %>

  <div class="col-sm-offset-2 col-sm-10">
     <%= form.text_field :nome, placeholder: "Informe o seu Nome", class: "form-control row" %>
  </div>

  <div class="col-sm-offset-2 col-sm-10">
    <%= form.number_field :idade, placeholder: "Digite sua idade", class: "form-control row" %>
  </div>

  <div class="col-sm-offset-2 col-sm-10">
    <%= form.number_field :cpf, placeholder: "Digite seu CPF", class: "form-control row" %>
  </div>

   <div class="field">
    <%= form.label :planos %>
    <%= form.select :planos, options_for_select([["Plano Plus", "plus"], ["Plano Light", "light"]]) %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar", class: "btn btn-primary" %>
    <%= link_to "Back to clientes", clientes_path, class: "btn btn-secondary" %>
  </div>
<% end %>
<form>
</div>

app/views/clientes/edit.html.erb
<%= render "form", cliente: @cliente %>

<br>

app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<div id="clientes">
  <% @clientes.each do |cliente| %>
    <%= render cliente %>
      <%= link_to "Ver cliente", cliente, class: "back-button" %>
  <% end %>
</div>

app/views/clientes/new.html.erb
<%provide(:title, 'Cadastro') %>

<%= render "form", cliente: @cliente %>

<br>

app/views/clientes/show.html.erb
<p class="success-notice"> <%= notice %> </p>

<div class="client-info">
  <%= render @cliente %>
</div>

<div class="buttons-container">
  <button class="edit-button" onClick="location.href='<%= edit_cliente_path(@cliente) %>'">Editar cliente</button>
  <button class="back-button" onClick="location.href='<%=clientes_path%>'">Voltar para clientes</button>
  <button class="delete-button" onClick="location.href='<%= (@cliente) %>', {method: :delete}">Excluir cliente</button>
</div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>

<html>
  <head>
    <title><%= yield(:title) %> | Academia F&G</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

    <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/3df637a2f2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="style.css">
    <title>Page Academia </title>
</head>
<body>
    <header>
        <div class="menu-content">
            <h1 class="logo">Academia F&G </h1>
            <nav class="header-menu">
                <ul class="list-itens">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Planos", planos_path %></li>
                    <li><%= link_to "Admin", "/admin" %></li>
                </ul>
            </nav>
        </div>
    </header>
    <% if request.path == root_path %>
    <main>
        <div class="main-content">
            <h1 class="primary-text">Treinar não fica mais fácil, você que fica melhor!</h1>
            <h2 class="second-text">SE INSCREVA AGORA E MUDE DE VIDA</h2>
            <div class="btns">
                <%= link_to "Cadastre-se", "/clientes/new", class: "btn-personal" %>
                <%= link_to 'Aulas e Treinos exclusivos', aulas_path, class: "btn-personal" %>

            </div>
        </div>
    </main>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
</body>
</html>

app/views/static_pages/about.html.erb
<%provide(:title, 'About') %>

<h2 class="second-text">Trabalho desenvolvido, para fins avaliativos referente a terceira nota de Programação III</h2>

app/views/static_pages/help.html.erb
<% provide(:title, "AA") %>
<h1>Help</h1>
<p>
  Check the rails guides and docs for help.
</p>

app/views/static_pages/home.html.erb
<%provide(:title, 'Home') %>
 

app/views/static_pages/planos.html.erb
<%provide(:title, 'Planos') %>
<div>
<h1> CONHEÇA NOSSOS PLANOS!</h1>
</div>
<hr>

<%= link_to "/clientes/new" do %>
  
  <div class="btns">

  <%= image_tag("planos/plano_light", class: "photo") %>

  <%= image_tag("planos/plano_plus", class: "photo") %>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>